include $(CLEAR_VARS)
LOCAL_SRC_FILES := libgbp_shim.cpp
LOCAL_MODULE := libgbp_shim
LOCAL_MODULE_TAGS := optional
LOCAL_PROPRIETARY_MODULE := true
LOCAL_VENDOR_MODULE := true
include $(BUILD_SHARED_LIBRARY)
